### ISSUE TITLE
Connect the server with client

### ISSUE THREAD

**Issue by z7pz** [itchatapp/client#37]
# ROADMAP
- [x] create the itchat client 
- [ ] #57
- [x] handle servers
- [x] handle user stats 
- [ ] #55
- [ ] #56
- [ ] #54
- [ ] send messages
- [ ] send files
- [ ] send voice messages
- [ ] join and talk in a voice chat

### Related issues
- itchatapp/itchat.js#4

### Useful links 
- [documentation](https://docs.itchat.world)
