### ISSUE TITLE
create messages

### ISSUE THREAD

**Issue by z7pz** [itchatapp/client#42]
# ROADMAP
- [x] add default message
- [ ] add files message
- [ ] add voice message
