### ISSUE TITLE
Refactor routing

### ISSUE THREAD

**Issue by z7pz** [itchatapp/client#62]
# ROADMAP:
- [x] Make it in a different folders/files
- [x] Make the app route and has those routes
- [ ] you done? (more changes)
